services:

  mariadb:
    build: ./requirements/mariadb
    secrets:
      - db_password
      - db_root_password
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file: .env
    restart: unless-stopped
    expose:
      - "3306"

  nginx:
    build: ./requirements/nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    env_file: .env
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: unless-stopped

  wordpress:
    build: ./requirements/wordpress
    secrets:
      - wp_admin_password
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    depends_on:
      - mariadb
    restart: unless-stopped
    expose:
      - "9000"
    

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/krfranco/data/mariadb

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/krfranco/data/wordpress

networks:
  inception:
    driver: bridge

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt
  wp_admin_password:
    file: ./secrets/wp_admin_password.txt